name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # schedule:
  #   - cron: '* * * * *'
  #? minute - hour - day - month - day of week
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project chromium
      - uses: actions/upload-artifact
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30